### ISSUE TITLE
Error on importing

### ISSUE THREAD

**Issue by hkedia321** [homfen/react-colorpicker#1]
I imported this package using:
`npm install react-input-colorpicker --save`
and tried it using. But the following error is coming:
![image](https://user-images.githubusercontent.com/17807257/40890822-ca2178b0-6799-11e8-986e-4a5088c3103c.png)
Please tell me how to filx this.

**Comment by kovloq** [comment]
Also happened to me.

**Comment by homfen** [comment]
You can configure Babel to handle the ES6 destructuring.
